apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: ls1-jan172026
  janus-idp.io/tekton: ls1-jan172026
  backstage.io/kubernetes-id: ls1-jan172026
  backstage.io/kubernetes-namespace: hello
  app.kubernetes.io/part-of: ls1-jan172026
resources:
  - application-dev.yaml

